### ISSUE TITLE
LAB_AK_07_Lab7_Ex3_Message_Encryption.md/Task 2/Step 5-9

### ISSUE THREAD

**Issue by AnthonyOakley** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#46]
# Module:  07
##### Step: 5-9

Description of issue
Kept getting access denied error

**Comment by LewisGoDeploy** [comment]
Experienced the same. Have tried Holly Dixon account and the tenant admin credentials.

**Comment by tfrink** [comment]
Thank you for bringing this to our attention. Microsoft has just released documentation indicating the authentication method used in this task is being deprecated. You could still use the old instructions if you assign the Exchange Admin role to Holly. However, because this authentication method is being deprecated, we chose not to go that route. Instead, we updated the instructions to follow Microsoft's new guideline:  

https://learn.microsoft.com/en-US/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps#appendix-comparison-of-old-and-new-connection-methods

In the revised instruction, we have the user install and connect to the Exchange Online PowerShell module (ExchangeOnlineManagement). We then revised the New-TransportRule command by swapping out properties. The revised command is now:

New-TransportRule -Name "Encrypt rule for Guest Services" -SentTo "[Gservices@adatum.com](mailto:Gservices@adatum.com)" -SentToScope "NotinOrganization" -ApplyRightsProtectionTemplate Encrypt

This command is similar to the old one, but we replaced the ApplyOME property (which we set to True) with the ApplyRightsProtectionTemplate property. While the ApplyOME property still works, if you use it, PowerShell returns a message indicating the ApplyOME property is being deprecated in favor of the ApplyRightsProtectionTemplate property. We chose to go with this property, and we assigned it the Encrypt template, which is the default encryption template.
