### ISSUE TITLE
LAB_AK_08_Lab8_Ex2_Test_DLP_Policy.md/Task 1-2

### ISSUE THREAD

**Issue by AnthonyOakley** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#47]
# Module:  08
##### Step: 

Description of issue
Task 1 Step 4 - Policy tip did not display
Task 1 Step 13 - Email delivery failed
Task 2 Step 2 - Policy tip did not display
Task 2 Step 3 - Did not get send blocked
Task 2 Step 4 - Email was sent instead of blocked
Task 2 Step 5 - Email made it to inbox
Skipped rest of steps in Lab 8.

**Comment by tfrink** [comment]
Lab testing has shown that DLP policies can be a hit or miss thing in our VM lab environment with our trial tenants. Earlier testing just a couple of weeks ago showed that this lab worked. It has been a staple of MS-101 for 3 years now, and it consistently worked. However, at times this type of behavior occurs, where policy tips don't display and policy rules are not applied. In discussing this with the Security team, they have experienced similar issues with their DLP labs. Sometimes they work, and sometimes they don't. Apparently there are throttling issues within our VM lab environment that affect DLP policies and sensitivity label policies. For now, we are leaving the lab as is. However, we will keep an eye on this issue to see if it becomes a larger problem or if it fails to correct itself.

**Comment by tfrink** [comment]
In following the lead of the Security team and how they handle this with their DLP labs, we added the following note at the start of the lab instructions for this exercise:

NOTE: We have intermittently experienced issues in the past where DLP policies and policy tips do not work as expected in this lab exercise. This is due to throttling issues that sometimes occur between our VM lab environment and the Microsoft 365 trial tenant. This is not indicative of the normal experience within Microsoft 365 production environments. It is also not indicative of the normal training experience. We apologize if you experience this issue.
