### ISSUE TITLE
LAB_AK_09_Lab9_Ex1_Implement Sensitivity labels.md/Task 04/Step 07

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#49]
# Lab/Demo: 09
#### Step: 07

We need to download the document file otherwise the sensitivity label settings will not show up.
![image](https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/assets/133017642/ba97d8d4-5e92-4cf0-b5af-0e656be3d286)

![image](https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/assets/133017642/69db7b68-25d0-4bc7-ba35-905fe18cd76d)

**Comment by tfrink** [comment]
Thank you for bringing this to our attention. We have updated the lab steps to address this issue. The problem is that by default, Word Online does not display watermarking in Normal reading view. So we updated the lab steps to have students go into the Additional Reading view, which displays the watermarks. Obviously, this is not ideal, since it would be better to see the watermarks and the sensitivity label applied as you're working on the doc in Normal view. Had we used the desktop version of Word, we wouldn't have run into this situation, since the Normal reading view displays watermarking by default. However, at this point it would be a much larger change to install Word on LON-CL1 just for this issue, so we chose to have students go into the Additional Reading view. We added a note to the lab instructions explaining this issue.
