### ISSUE TITLE
Issue Learning Path 1 - Lab 1 - Exercise 2 - Manage Users and Groups

### ISSUE THREAD

**Issue by henrikmai** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#57]
On Task 4 Step 8 the Restore is not possible, because the command or commandlet
` Restore-MgDirectoryDeletedItem -DirectoryObjectId $DeletedGroup.id`
is not known.
That´s the same for all my students an me.

![image](https://github.com/MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials/assets/29449777/47bea0cc-f001-4569-9345-ccc8b113435f)

**Comment by tfrink** [comment]
Looking into it now. Thanks!

**Comment by tfrink** [comment]
In Lab 1, Exercise 1, there's a task where you install Microsoft Graph PowerShell. The Install command displays the 30+ sub-modules that get installed, one of which is Microsoft.Graph.Identity.DirectoryManagement. This sub-module contains the Restore cmdlet used in the task you called out that restores the deleted group. What we discovered is that if you run PowerShell in a non-admin state (i.e. by not selecting "Run as administrator" when starting PowerShell), then the Install command doesn't install the DirectoryManagement sub-module. Not sure if that's what happened with you and your class, but for some reason that module didn't get installed. So what we're doing is updating the lab instructions so that after installing Microsoft Graph PowerShell, we going to have the students verify that the Directory Management module is installed, and if not, then we're providing PowerShell instructions that install that specific module. That should resolve this issue.
