### ISSUE TITLE
Learning Path 2 - Lab 2 - Exercise 1

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#62]
# Module: 01
## Lab/Demo: 01
Task 2 Step 7 and 12

Description of issue. The command given is generic and only gives ti id not the displayname . Please make it easier on students and change command to

Learning Path 2 - Lab 2 - Exercise 1 Task 2 Step 7 and 12

 Get-MgDirectoryRole  | fl id, displayname

Also step 8 would be easier if they filtered on the role name  

Get-MgDirectoryRoleTemplate | ? DisplayName -eq "Service Support Administrator"

**Comment by tfrink** [comment]
Thanks Mike! I'll look into this and make the necessary updates.

**Comment by LewisGoDeploy** [comment]
I have noticed if you run the command with powershell in full screen mode you will see the role name. Could be mentioned in the guide though.

**Comment by tfrink** [comment]
Thank you both for your suggestions. 

LewisGoDeploy - I added your note to view the PowerShell window in full screen mode to see the role name. That addressed MikeVeshi's note on steps 7 and 12.

MikeVeshi - regarding step 8, I loved your suggestion, since it saves the student from having to scroll through the list of role templates to find the Service Support admin template. However, to maximize the student's learning experience, especially for students who are maybe not quite as familiar with PowerShell, I updated step 8 to have them run BOTH PowerShell commands. I first have them run the existing command to see the complete list of role templates. I then explain that while it's important to know this command since it can prove useful at times, in this case, since you're looking for a specific role, it would be more efficient to run the command that you proposed. So then I have them run your command. It should only take a minute or so more to run both commands, but by doing so, I think it can maximize the learning experience for the students. 

I will be releasing the updated instructions the weekend of 12/16 so as not to interfere with ongoing courses this week.
