### ISSUE TITLE
Lab 5: Safe Links policy

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#66]
# Module: 5
## Lab/Demo: 5
##Exercise: 2

In Lab 5, Ex 2, Task 1 you create a Safe Links policy.  In Task 2 you test it - Holly sends an email to MOD Admin containing a link to www.tailspintoys.com.  When MOD Admin clicks on the link in the email, Safe Links is supposed to step in and show a message saying that the link is suspicious.

However, the email is never delivered to MOD Admin.

No email containing a link to tailspintoys.com is ever delivered. I've tried sending from a Gmail account to MOD Admin, and also tried to send to other internal users, but the emails are always blocked.

It isn't a timing issue, as I've tried sending the emails several days later.

A colleague has seen this lab work in the past, but suspects that in new tenants, Microsoft's spam filters are blocking emails containing this URL.  Is there any way this could be modified so that the lab will work, and the email will be delivered to MOD admin?

**Comment by MikeVeschi** [comment]
Same here no emails are delivered inbound

**Comment by tfrink** [comment]
The problem is that by adding the tailspintoys.com URL to the blocked URL list, the system was never going to send the email in the first place; actually, it attempted to send the email since it's in the Sent Items folder, but it was blocked from arriving in the MOD Admin's Inbox. I modified task 2 to perform the following steps to validate both the blocked URL functionality and the Safe Links policy:

1. First, you will send two emails from Holly Dickson to the MOD Administrator - one that contains an unblocked URL (http://adatum.com/aboutus) and another that contains the blocked http://tailspintoys.com/ URL.
2. You will verify that both emails appear in Holly's Sent Items folder.
3. You will then log into the MOD Administrator's Outlook mailbox and verify that the email with the unblocked URL arrived in the MOD Administrator's Inbox and the email with the blocked URL never arrived. This verifies two things - first, the email system is working properly since the email with the unblocked URL arrived in the MOD Admin's Inbox. Second, the fact that the system sent the email with the blocked URL but it never arrived in the MOD Administrators Inbox verifies the Blocked URL functionality worked.
4. You will then go back into Holly's Outlook mailbox and open the email in her Sent Items folder that contains the blocked URL. You will select the hyperlinked text and verify the Safe Links policy worked when you try to access this blocked site.

I will be releasing the updated instructions the weekend of 12/16 so as not to interfere with ongoing courses this week.

**Comment by AnnetteGill** [comment]
Thank you very much!
