### ISSUE TITLE
Can't verify domain

### ISSUE THREAD

**Issue by mshoaib90** [MicrosoftLearning/MS-102T00-Microsoft-365-Administrator-Essentials#97]
# Module: Learning Path 1 - Lab 1
#### Step: 00

Description of issue : Couldn't verify the custom domain even after 24hrs.

Repro steps:

1.
1.
1.

**Comment by tfrink** [comment]
Our guess is that this is some form of tenant issue. Every month we have an external vendor test the labs for all our M365 courses. The most recent MS-102 test was just last week, and everything checked out OK. I was also doing some lab testing myself two weeks ago, and I personally tested this lab along with some others lab exercises and everything worked OK. However, I did notice a change in the response that I received when I verified the CNAME record. I updated the lab steps to mention that (see the final Note in step 33). However, I was able to complete the lab and verify the new domain.

I'm not sure what may have been the problem here for you. I haven't heard from any other MCTs, so at this point I can only assume it was a one-off incident. I'm not sure what else to say at this point since we didn't reproduce this issue in our recent testing.

Let me ask you this - what error messages did it give you when you tried to verify the domain? Maybe from that we can figure out what might have been causing the issue you had. Did you verify each DNS record and get the check mark after creating each? At what step(s) in the process did it fail to verify the domain?
